eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-comp-service
server:
  port: 7006
  servlet:
    context-path: /api/v1