eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-comp-service
server:
  port: 7006
  servlet:
    context-path: /api/v1
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include : health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      product-circuitbreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState : 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
