spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://localhost/review-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7001
  servlet:
    context-path: /api/v1